WORDS_PATH = "content/words.txt"
STATISTICS_PATH = "content/test_statistics.png"

TEST_TEXT_SIZE = 30
TEST_TEXT_AREA_WIDTH_K = 0.8
COURSOR_WIDTH = 1
TEST_GAP_BETWEEN_LINES_K = 1.5

STATISTICS_TEXT_SIZE = 20
STATISTICS_WORKING_AREA_WIDTH_K = 0.7
STATISTICS_PLOT_HEIGHT_K = 0.6
STATISTICS_PLOT_TOP_MARGIN_K = 0.1
STATISTICS_RESULTS_TITLES_TOP_GAP_K = 0.05
STATISTICS_RESULTS_TOP_GAP_K = 0.042
STATISTICS_RESTART_TOP_GAP_K = 0.1
